// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DataList: typeof import('./src/components/Home/DataList.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/Base/Footer.vue')['default']
    Header: typeof import('./src/components/Home/Header.vue')['default']
    Info: typeof import('./src/components/Home/Info.vue')['default']
    MineCard: typeof import('./src/components/Mine/MineCard.vue')['default']
    MineInfo: typeof import('./src/components/Mine/MineInfo.vue')['default']
    ProductCard: typeof import('./src/components/Card/ProductCard.vue')['default']
    ProductListView: typeof import('./src/components/Products/ProductListView.vue')['default']
    ReadingList: typeof import('./src/components/Home/ReadingList.vue')['default']
    Sample: typeof import('./src/components/sample.vue')['default']
  }
}

export { }
